# -*- coding: utf-8 -*-
"""测试套件归档：统一 figures 目录、JSON 报告、README 可替换区块。"""
import json
import shutil
import sys
import time
from pathlib import Path
from typing import Any, Dict, List, Optional

MARKER_BEGIN = "<!-- SUITE_ARTIFACTS_BEGIN -->"
MARKER_END = "<!-- SUITE_ARTIFACTS_END -->"


def artifact_dirs(repo: Path):
    root = repo / "test_artifacts"
    return root, root / "figures"


def ensure_dirs(repo: Path) -> tuple:
    root, figs = artifact_dirs(repo)
    figs.mkdir(parents=True, exist_ok=True)
    root.mkdir(parents=True, exist_ok=True)
    return root, figs


def archive_job_figure(
    repo: Path, figures_dir: Path, group: str, script: str, expect_png: Optional[str]
) -> Optional[str]:
    """
    将仓库根目录下 expect_png 复制到 test_artifacts/figures/{group}__{stem}.png。
    返回相对 repo 的路径（用于 README），失败返回 None。
    """
    if not expect_png:
        return None
    src = repo / expect_png
    if not src.is_file():
        return None
    stem = Path(script).stem
    dest_name = "%s__%s.png" % (group, stem)
    dest = figures_dir / dest_name
    shutil.copy2(str(src), str(dest))
    return "test_artifacts/figures/%s" % dest_name


def build_markdown(
    rows: List[Dict[str, Any]], suite_ok: bool, elapsed: float
) -> str:
    lines = [
        "## Automated test report / 自动化测试报告",
        "",
        "> 由 `python run_unified_suite.py` 生成；**请勿手改**本段，重跑套件即可刷新。",
        "> Generated by the unified suite; **do not edit**—re-run to refresh.",
        "",
        "- **时间 / Time:** %s" % time.strftime("%Y-%m-%d %H:%M:%S"),
        "- **Python:** %s" % sys.version.split()[0],
        "- **结果 / Outcome:** %s" % ("SUITE_PASS" if suite_ok else "SUITE_FAIL"),
        "- **总用时 / Total:** %.1f s" % elapsed,
        "",
        "### Figures / 图（`test_artifacts/figures` 归档）",
        "",
    ]
    for r in rows:
        rel = r.get("archived_figure")
        status = r.get("status", "?")
        title = r.get("title", "")
        script = r.get("script", "")
        reason = (r.get("reason") or "").replace("\n", " ")
        if len(reason) > 480:
            reason = reason[:477] + "..."
        lines.append(
            "**[%s]** %s — `%s`"
            % (status, title or script, script)
        )
        lines.append("")
        if rel:
            lines.append("![%s](%s)" % (Path(rel).stem, rel))
        else:
            lines.append("*（无图或未生成 expect_png）*")
        lines.append("")
        lines.append("*门禁 / Gate:* %s" % reason)
        lines.append("")
        log = r.get("stdout_tail") or ""
        if log:
            body = log[:6000]
            if len(log) > 6000:
                body += "\n... [truncated]"
            lines.append(
                "<details><summary>stdout 摘要 / log tail</summary>\n\n```\n%s\n```\n</details>\n"
                % body
            )
            lines.append("")
    lines.append("---\n")
    lines.append(
        "机器可读完整记录见 [`test_artifacts/suite_report.json`](test_artifacts/suite_report.json)。\n"
    )
    return "\n".join(lines)


def write_report_json(path: Path, payload: Dict[str, Any]) -> None:
    path.write_text(
        json.dumps(payload, ensure_ascii=False, indent=2),
        encoding="utf-8",
    )


def patch_readme(readme_path: Path, md_block: str) -> None:
    text = readme_path.read_text(encoding="utf-8")
    if MARKER_BEGIN in text and MARKER_END in text:
        pre, rest = text.split(MARKER_BEGIN, 1)
        _, post = rest.split(MARKER_END, 1)
        new = pre + MARKER_BEGIN + "\n\n" + md_block + "\n\n" + MARKER_END + post
    else:
        new = text.rstrip() + "\n\n" + MARKER_BEGIN + "\n\n" + md_block + "\n\n" + MARKER_END + "\n"
    readme_path.write_text(new, encoding="utf-8")
