#!/usr/bin/env python3
"""
GHZ Final Paper Visualizer — v19 Edition
----------------------------------------
PURPOSE: Generate the definitive figure for the GHZ Deconstruction Paper.
Visualizes the 'Chain Explosion' (v19) model where a geometric loop 
combined with a threshold trigger yields F=4.0.
"""

import numpy as np
import matplotlib.pyplot as plt
from pathlib import Path

def generate_final_paper_figure():
    res = 80
    limit = 10.0
    x = np.linspace(-limit, limit, res)
    y = np.linspace(-limit, limit, res)
    z = np.linspace(-limit, limit, res)
    X, Y, Z = np.meshgrid(x, y, z)
    
    # 3 Sources in a Triangle (The Loop)
    d_src = 3.0
    sources = [
        (d_src * np.cos(0),           d_src * np.sin(0),           0.0),
        (d_src * np.cos(2*np.pi/3),   d_src * np.sin(2*np.pi/3),   0.0),
        (d_src * np.cos(4*np.pi/3),   d_src * np.sin(4*np.pi/3),   0.0)
    ]
    
    # Observers
    r_det = 7.5
    detectors = [
        (r_det * np.cos(np.pi/3),     r_det * np.sin(np.pi/3),     0.0),
        (r_det * np.cos(np.pi),        r_det * np.sin(np.pi),        0.0),
        (r_det * np.cos(5*np.pi/3),   r_det * np.sin(5*np.pi/3),   0.0)
    ]
    
    out_dir = Path("visualizations/ghz_final_v19_paper")
    out_dir.mkdir(parents=True, exist_ok=True)
    
    k = 5.0
    omega = 0.0 # Snapshot of resonance
    
    # Calculate the v19 field: Phase Loop
    # In v19, Alice measures L1-L2. For the visual, we simulate the interference pattern
    # generated by these three locked sources.
    Psi_Total = np.zeros_like(X)
    for sx, sy, sz in sources:
        dist = np.sqrt((X - sx)**2 + (Y - sy)**2 + (Z - sz)**2)
        # We assume the sources are phase-locked in a loop
        Psi_Total += (1.0 / (dist + 0.1)) * np.cos(k * dist)
        
    Energy = Psi_Total**2
    
    fig = plt.figure(figsize=(12, 12), facecolor='black')
    ax = fig.add_subplot(111, projection='3d', facecolor='black')
    
    # 1. The 'Chain Explosion' Volumetric Burst (F=4.0 Engine)
    # Thresholding at 99th percentile to show only the perfect resonance spots
    threshold = np.percentile(Energy, 98.5)
    mask_burst = Energy > threshold
    ax.scatter(X[mask_burst], Y[mask_burst], Z[mask_burst], 
               c=Energy[mask_burst], cmap='YlOrRd', s=10, alpha=0.4, edgecolors='none')

    # 2. Wavefront Interference Texture (The 'Chaotic' Reality)
    slice_idx = res // 2
    ax.contourf(X[:,:,slice_idx], Y[:,:,slice_idx], Psi_Total[:,:,slice_idx], 
                levels=30, cmap='inferno', alpha=0.15, offset=-limit)

    # 3. Topology Lines (The 3-Stone Loop)
    for j in range(len(sources)):
        s1 = sources[j]
        s2 = sources[(j+1)%len(sources)]
        ax.plot([s1[0], s2[0]], [s1[1], s2[1]], [s1[2], s2[2]], 'w-', lw=2, alpha=0.6, label='Phase Loop' if j==0 else "")

    # 4. Markers
    for dx, dy, dz in detectors:
        ax.scatter(dx, dy, dz, color='cyan', s=250, marker='X', edgecolors='white', zorder=20)
    for sx, sy, sz in sources:
        ax.scatter(sx, sy, sz, color='gold', s=150, marker='o', edgecolors='white', zorder=20)

    ax.view_init(elev=30, azim=40)
    ax.set_xlim(-limit, limit)
    ax.set_ylim(-limit, limit)
    ax.set_zlim(-limit, limit)
    ax.set_title("GHZ Deconstruction: The Chain Explosion at Resonance (F=4.0)", color='white', fontsize=16)
    ax.axis('off')
    
    plt.tight_layout()
    final_path = out_dir / "GHZ_FINAL_V19_FIGURE.png"
    plt.savefig(final_path, dpi=200, facecolor='black')
    plt.close()
    
    print(f"Final Paper Figure saved to {final_path}")

if __name__ == "__main__":
    generate_final_paper_figure()
